### ISSUE TITLE
Crear Pagina de revistas

### ISSUE THREAD

**Issue by josearangos** [ealejandro101/journal-research-client#12]
- [x] Header Research
- [x] Componente de busqueda
- [x] Componente de card journal summary
- [x] Filta en el apartado izquierdo, solo por categoría

**Comment by jasolutions** [comment]
Hola Jose

https://www.dropbox.com/sh/9c0w1l4jl2ez8i6/AADgp7_CIocnN8i3t38VEwVEa?dl=0

Aqui cargue un sql. con algunas revistas... es que las del formulario estan incompletas  me cuentas como se ve porfa...
