### ISSUE TITLE
Cambios del portal

### ISSUE THREAD

**Issue by jasolutions** [ealejandro101/journal-research-client#14]
- [x] Hacer que la pagina se vea  en desde un pc, ahora solo se ve desde un movil.

- [x] Mostrar las categorias (8) de las revistas en la pagina principal

- [x] En la pagina del listado de revistas debe estar una corta descripción, con el issn y el doi

- [x] Al elegir una revista esta debe contar con una pagina web a la que alguien pueda ingresar directamente

- [x] Cuando ingreso a una revista y las demás pasan a columna izquierda, ponerla mas pequeña

- [x] No se ve toda la información de las revistas una vez se ingresa a esta

- [x] Es posible poner predicción al momento de buscar una revista (que inicio a poner la palabra y me trae las revistas que tienen esas palabras)

**Comment by ealejandro101** [comment]
Coloque cada item como issues indivicuales
