### ISSUE TITLE
En la pagina del listado de revistas debe estar una corta descripción, con el issn y el doi

### ISSUE THREAD

**Issue by ealejandro101** [ealejandro101/journal-research-client#18]

**Comment by ealejandro101** [comment]
Debajo del titulo debe aparecer el DOI e ISSN, en el tipo de letra que este descripción.
Disminuir el tipo de letra de descripción

**Comment by ealejandro101** [comment]
Orden.
eISSN: xxx.xxxx.xxx | DOI: 10.xxx.xx
ISSN: xxx.xxxx.xxx | DOI: 10.xxx.xx
ISSN: xxx.xxxx.xxx 
eISSN: xxx.xxxx.xxx 

Tener en cuenta que el DOI es un enlace

**Comment by ealejandro101** [comment]
el DOI acá no es enlace

**Comment by cristianmarind** [comment]
Las siguientes son las horas previstas que vamos a destinar a este issue: 0.5 horas
Porfavor aprobar o rechazar el total de horas.

**Comment by jasolutions** [comment]
Este punto también se tenia para la primera entrega.
Aprobado
