### ISSUE TITLE
Mockup del sistema

### ISSUE THREAD

**Issue by cristianmarind** [ealejandro101/journal-research-client#3]
Se realizará el prototipo visual del sistema con el fin de visualizar previo al desarrollo un acercamiento de como se verá la plataforma; para que Journal Research valide si el diseño propuesto suple las necesidades del proyecto.

En los mockups se tendrán en cuenta las siguientes funcionalidades del sistema:

1. Apartado información base
- Apartado de ¿qué hacemos?
- Apartado de ¿quienes somos?
- Apartado de contacto
- Apartado de redes sociales
- Apartado de COPYRIGHT y PÁGINAS LEGALES

2. Sección de revistas
- Filtros de búsquedas por Título / Subtitulo / Subtitle  - Título Corto -  Periodicidad - Responsable -
 Institución (facultad, institución) - Categoría - País - Ciudad - Licencia Creative Commons  - Política de Autoarchivo   
- Estadísticas que se indique cuantas revistas hay por país, por categoría, por institución.
- Información de cada revista (mejorando la parte visual), tomando en cuenta los datos capturados, la sinopsis y presentación de la carátula de la revista

3. Sección de solicitud de ingreso de revistas a ResearcH
- Formulario web para que el personal de la revista realice la solicitud.

Para esta actividad los desarrolladores Cristian Marín y Jose Arango van a invertir un total de 2 horas cada uno, realizando un prototipo con transiciones y navegabilidad, el cual podrán probar mediante un navegador web.

Quedamos atentos a la aprobación u alguna observación de este Issue.

**Comment by jasolutions** [comment]
Tener en cuenta que en el apartado información base, la mayoría de esta información seria encontrada en nuestra web actual que esta sobre wordpress, creo que no seria necesario replicarla. (http://jasolutions.com.co)

**Comment by josearangos** [comment]
Perfecto, entonces solo nos centraremos en los demás apartados.

**Comment by jasolutions** [comment]
Si, esta bien se aprueban las horas destinadas.

**Comment by josearangos** [comment]
A continuación anexamos los mockups o vistas con la simulación, estamos atentos a su feedback 
https://marvelapp.com/4h69d23/screen/47404522

**Comment by cristianmarind** [comment]
Saludos, según la reunión del día 7 de septiembre, se realizarán las correcciones a los Mockups pactadas ese día. 
Para esta actividad los desarrolladores Cristian Marín y Jose Arango van a invertir un total de 2 horas cada uno.

Aspectos a corregir:
Reconstrucción del HOME 
* Menú empresa , menú del sistema con las siguiente opciones : (que es+políticas, postular revista, registrase, inicio de sesión, buscador+ir a filtros avanzados)
* Banner con una imagen o vídeo
* Buscador con la opción de filtros
* Sección de Paso a Paso con  estadísticas al lado: estas seria un mapa y cifras(total de revistas, total artículos)
* Sección de ultimas revistas
* Sección de ultimas convocatorias

Reconstrucción de la sección de información de la revista, que incluye:
* Añadir cantidad de artículos de la revistas, si la revista tiene o no convocatoria
* Con los siguiente logos (una bocina roja si tiene convocatoria activo activa y una bocina gris si es permanente)
* Botón de seguir revista

Sección de la lista de artículos que tiene la revista con un filtro de búsqueda para estos

Anexo los apuntes de la reunión. 
https://drive.google.com/a/udea.edu.co/file/d/1DsZb2AWcySXCka6BifvkvoeXflR8rJRa/view?usp=sharing 

Información faltante:
* Procesos tanto del investigador como del editor
* Multimedia/Colores/etc de ResearcH
* Definición de filtros para las revistas y para los artículos (nombres y opciones)

**Comment by jasolutions** [comment]
Cordial saludo
Aprobamos las horas para las modificaciones.

Nota aclaratoria: Solo publicaremos las convocatorios que tengan fecha de inicio y fecha final, las convocatorias permanentes no se publicaran. Solo usariamos entonces el parlantico en rojo.

La url del formulario actualizado:
http://journals-research.com/acuerdo_research.html

A continuación detallamos los filtros de búsqueda y sus opciones de elección:
- CFP (Call for papers)
   ° Traera todas las revistas que tienen cfp

- Categoría
   ° Muestra las 8 categorías del sistema

- Periodicidad
   ° mostrará las opciones de periodicidad del sistema

- APCs
  ° Si
  ° No

- Indexaciones
  ° WOS
  ° Scopus
  ° ECSI
  ° Redalyc
  ° SciELO
  ° DOAJ

- País
Apareceran los países de los cuales tenemos revistas, tomado de la base de datos

- Idioma
  Apareceran los idiomas tomados de la base de datos (Español, ingles, portugues, frances, otro)

Filtros secundarios (que no son muy usados)
- Licencia CC
  Aparecen los tipos de licencia del sistema

- Institución

- Política de autoarchivo


xoxoxoxoxoxoxoxoxoxoxoxoxoxoxoxoxoxoxoxoxoxoxoxoxoxoxoxoxoxoxoxoxoxoxoxoxoxoxox

El usuario debe poder buscar por:

Categoría
Título
Palabra clave
País

xoxoxoxoxoxoxoxoxoxoxoxoxoxoxoxoxoxoxoxoxoxoxoxoxoxoxoxoxoxoxoxoxoxoxoxoxoxoxox

Postulación:
1. El editor diligencia el formulario de postulación de la revista.
2. J&A realiza una validación de la información para aceptar o no la revista en el sistema.
3. SI se valida la revista ya queda publicada en el sitio.
4. El editor quedará con un usuario (el de la revista) que le permitirá ver la información actual de la revista y solicitar actualizaciones de la misma.
4. Dentro del perfil del usuario revista el editor podrá enviar convocatorias... ¿Desea publicar un CFP?
 4.1 si desea agregar un CFP lo lleva al formulario de la convocatoria
 4.2 diligencia el formulario, los campos repetidos debe copiarlos de la base de datos para que el usuario no tenga que repetirlos.
 4.3 El CFP pasa a cola de aprobación por J&A.
 4.4 Si se acepta se publica, sino el editor puede corregirla.

Se debe activar el megafono en la pagina de la revista y aparecer en ultimas convocatorias.
Una vez pase el tiempo se debe desactivar el megafono y desaparecer del sitio, mas no del perfil de la revista.


El formulario de la convocatoria tendrá: 
un campo de Descripción de la convocatoria (obligatorio) máximo 250 palabras, 
Fecha inicial y fecha final de la convocatoria (obligatorio), 
URL del CFP de mas información
un campo para adjuntar video o ecard de invitación a publicar y 
un botón de contactar al editor. 

xoxoxoxoxoxoxoxoxoxoxoxoxoxoxoxoxoxoxoxoxoxoxoxoxoxoxoxoxoxoxoxoxoxoxoxoxoxoxox

Cualquier usuario podrá usar el sistema sin necesidad de estar logueado, se usara el login cuando el autor, investigador o cualquiera desee recibir alertas del sistema.

Proceso del investigador (o cualquier usuario)
- debe poder crear un usuario
- correo de bienvenida y activación de la cuenta
- Como usuario podrá usar el sistema normalmente, y adicional
- suscribirse a las revistas de su interés para generar alertas
- conservar sus búsquedas (historial)

xoxoxoxoxoxoxoxoxoxoxoxoxoxoxoxoxoxoxoxoxoxoxoxoxoxoxoxoxoxoxoxoxoxoxoxoxoxoxox

El formulario de registro tendra:  (o no se si se pueda poner entrar con google, con facebook, jeje no se como funcione)

Nombre
Apellidos
Email
País (controlado)
Ciudad (controlado)
OrciD
si tiene perfil en Redalyc indique la url
Nivel de estudio: Pregrado, Maestría, Doctorado, Posdoctorado, otro.
Posición actual: estudiante, profesor, editor, otro.
cargar imagen: 

usuario
contraseña

Áreas de interés (son las 8 categorías de las revistas)
Disciplina

Como escucho de nosotros:
Evento académico, Facebook, Twitter, google, referencia de un colega, otro_____


Un check de aceptación del envío de información de J&A

Captcha.

xoxoxoxoxoxoxoxoxoxoxoxoxoxoxoxoxoxoxoxoxoxoxoxoxoxoxoxoxoxoxoxoxoxoxoxoxoxoxox

Ya en nuestra interfaz de administradores debemos poder ver la información de los usuarios, y saber por ejemplo cuantos estan interesado en x o y categoría, cuantos son de maestría, o de doctorado. 
Incluso poder construir un mapa donde se pueda ver que autores estan interesados en ingenieria por ejemplo y a esos son los que les llegara el cfp..

**Comment by josearangos** [comment]
Cordial Saludo

En el siguiente enlace podrán visualizar los nuevos diseños: https://marvelapp.com/4h69d23

Queda pendiente las siguientes cosas:

- Criterios de filtros para los artículos de las revistas
- Toda los recursos multimedia con los que cuenten de research
-Para el filtro de Política de autoarchivo cuales son las opciones

Estamos atentos a las observaciones.

**Comment by jasolutions** [comment]
Hola

Este es el enlace en drop para descargar los archivos multimedia:
[https://www.dropbox.com/sh/9c0w1l4jl2ez8i6/AADgp7_CIocnN8i3t38VEwVEa?dl=0](https://www.dropbox.com/sh/9c0w1l4jl2ez8i6/AADgp7_CIocnN8i3t38VEwVEa?dl=0)

El filtro de política de autoarchivo es: Verde, Azul, Amarillo, Blanco

**Comment by jasolutions** [comment]
Hola todos

Se me ol
