### ISSUE TITLE
Detalle de la revista y texto de descripción

### ISSUE THREAD

**Issue by ealejandro101** [ealejandro101/journal-research-client#34]
En el detalle de cada revista colocar la imagen en la misma columna pero arriba y que el texto rodee la imagen

**Comment by cristianmarind** [comment]
Las siguientes son las horas previstas que vamos a destinar a este issue: 0,25 horas
Porfavor aprobar o rechazar el total de horas.

**Comment by jasolutions** [comment]
Aprobado
