### ISSUE TITLE
Separar el logo de la caja del buscador

### ISSUE THREAD

**Issue by ealejandro101** [ealejandro101/journal-research-client#35]

**Comment by ealejandro101** [comment]
Separar el logo de la caja de buscador
La marce de agua de la caja debe decir:
"Titulo - Descripción"

La marca de agua dice
Titulo, Palabra Clave Institución

Esta busqueda aún se realiza por BD.

**Comment by cristianmarind** [comment]
Las siguientes son las horas previstas que vamos a destinar a este issue: 0.2 horas
Porfavor aprobar o rechazar el total de horas.

**Comment by jasolutions** [comment]
aprobado
